### ISSUE TITLE
please provide installer.py not only the install_driver.exe in release pack

### ISSUE THREAD

**Issue by CrystalRays** [ju1ce/April-Tag-VR-FullBody-Tracker#99]
if there is any chinese character in steamvr.vrsettings, it raises an exception like this.

exception:
```bash
Traceback (most recent call last):
  File "installer.py", line 60, in <module>
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 1031: illegal multibyte sequence
[13936] Failed to execute script installer
```

the exception occour on line 59 in installer.py

```python
with open(config) as f:
    config_data = load(f)
```

we need change these line to fix as below

```python
with open(config,encoding="utf-8") as f:
    config_data = load(f)
```

**Comment by CrystalRays** [comment]
pls also update mediapipe project
